version: "3.9" 
services:
  web:
    build: .
    ports:
      - "23580:3000"
      - "9229:9229"
    volumes:
      - ./src:/app/src
      - ./downloads:/home/pptruser/Downloads
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - logvolume01:/var/log
    links:
      - redis
    command: npm run start
    env_file: .env
  redis:
    image: redis:6.2.6-alpine
volumes:
  logvolume01: {}