version: "3.9" 
services:
  web-and-crawler:
    build: .
    ports:
      - "23580:3000"
      - "9229:9229"
    volumes:
      - ./src:/app/src
      - ./downloads:/home/pptruser/Downloads
      - ./migrations:/app/migrations
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - logvolume01:/var/log
    links:
      - redis
      - postgres
    command: sh -c "sleep 5 && npm run migrate up && npm run start"
    env_file: .env
  redis:
    image: redis:6.2.6-alpine
    volumes:
      - ./redis.conf:/var/lib/redis/redis.conf
    command: sh -c "redis-server /var/lib/redis/redis.conf"
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
volumes:
  logvolume01: {}